#!/bin/sh
/usr/bin/pacman -Qne > $HOME/.data/pacman/official_pkgs.txt
/usr/bin/pacman -Qme > $HOME/.data/pacman/aur_pkgs.txt
/usr/bin/pacman -Qii | awk '/^MODIFIED/ {print $2}' > $HOME/.data/pacman/changed_files.txt
/usr/bin/pacman -Qtdq > $HOME/.data/pacman/orphans.txt


