#!/usr/bin/env bash
set -euo pipefail

export PATH="/home/dani/Desktop/repos/eww/target/release:$PATH"

state=$(eww windows | grep power)

if [ "$state" == "*power" ]; then
    eww close power
else
    eww open power
fi
